#!/bin/tcsh

set soundfont = "$HOME/churchplayer/churchplayer.sf2"

#  Kill any processes that are using the audio device (hw:0)
killall -r -s KILL fluidsynth

set pid = `fuser -v /dev/snd/pcmC0D0p`
while( $status == 0 )
   kill $pid
   set pid = `fuser -v /dev/snd/pcmC0D0p`
end

#  Start up the server process that creates the sound from the ALSA sequencer
#  data. Read stdin commands from the above fifo.
/usr/bin/fluidsynth -f fluid.conf --server --audio-driver=alsa -o audio.alsa.device=hw:0 $soundfont $1 
